[package]
name = "guessing_game"
version = "0.1.0"
authors = ["Iftikhar uddin <iftikhar@connextar.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
colored = "2.0.0"